### ISSUE TITLE
Right sidebar looks like shit on my external display

### ISSUE THREAD

**Issue by jbowens** [jbowens/peernote#11]
:warning: 

![screen shot 2014-03-15 at 3 14 32 pm](https://f.cloud.github.com/assets/867352/2429279/220795ca-ac76-11e3-9feb-c408f7eeaef6.png)

**Comment by bryceAebi** [comment]
is this still an issue? i changed a lot of the css structure. it doesn't seem to have this problem on my external display

**Comment by jbowens** [comment]
no it doesn't look like it exists anymore, but when i open and close the comment dialog i do get this

![screen shot 2014-03-31 at 11 48 12 am](https://cloud.githubusercontent.com/assets/867352/2569364/0b962892-b8ec-11e3-942d-299bdf2c4139.png)

**Comment by bryceAebi** [comment]
ugh. what am i even supposed to do about that

**Comment by al63** [comment]
blame chrome
