### ISSUE TITLE
Pressing enter on Notepad creates new div

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#12]
the notepad is a contenteditable div. js from editor is affecting it i guess.

**Comment by jbowens** [comment]
confused... what's the problem? also is this on the master or editor branch?

**Comment by bryceAebi** [comment]
on master. the change isn't visible, but if you examine the html you see divs appearing

**Comment by jbowens** [comment]
This has always been the case. Is it undesirable?

**Comment by bryceAebi** [comment]
talking about the new notepad. It's in the right column. I guess there's no actual problem. It just seems a bit sketch

**Comment by jbowens** [comment]
Invalid
