### ISSUE TITLE
Editor in multiple tabs

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#14]
If you open two tabs for the same essay, whichever tab is written to last will be saved. This is awkward because lets say on tab1 you write one page, tab2 you write another page for the same essay. you close tab 2. then you accidentally press a key on tab1 and you've just lost that entire second page of your essay.  

Basically, the way to fix this, open essays should periodically make an AJAX request for the saved essay content.

**Comment by al63** [comment]
ill do eventually

**Comment by bryceAebi** [comment]
on another note, if the client finds that it is not connected to the internet it should open up a lightbox saying that the editor is not connected to the internet and prevent typing.

**Comment by bryceAebi** [comment]
these issues are all second priority to the tasks on trello

**Comment by bryceAebi** [comment]
im just writing them down because they'll need to be implemented at some point.

**Comment by bryceAebi** [comment]
is this closed?
