### ISSUE TITLE
splash page navbar email sign up broken in safari

### ISSUE THREAD

**Issue by jbowens** [jbowens/peernote#2]
In Safari, clicking on the email input field in the navbar doesn't move focus to the input field. Maybe the event is going to some other overlaying element? Shit is weird.

**Comment by jbowens** [comment]
I figured out the problem. It's the `-webkit-user-select: none;` property. Removing the property allows focus in Safari. See http://stackoverflow.com/questions/20495827/text-field-not-working-in-safari

**Comment by jbowens** [comment]
Fix plz @bryceAebi

**Comment by bryceAebi** [comment]
done

**Comment by jbowens** [comment]
Was fixed by d03d3629191
