### ISSUE TITLE
make honeypot for signup form

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#24]

**Comment by jbowens** [comment]
pourquoi? captcha not enough?

**Comment by bryceAebi** [comment]
https://github.com/jbowens/peernote/commit/94b0c1c4311b09503e2cd932be5f8770fda22fbd 

lol

**Comment by jbowens** [comment]
omg why

**Comment by jbowens** [comment]
you jerk

**Comment by bryceAebi** [comment]
![screen shot 2014-03-29 at 3 10 24 pm](https://cloud.githubusercontent.com/assets/3914975/2559291/d41e4ede-b775-11e3-9f02-d0942a875e22.png)

this looks a lot better. (my photo isn't centered btw)

**Comment by jbowens** [comment]
does it? where's catcher in the rye?

**Comment by bryceAebi** [comment]
we're in a brave new world

**Comment by jbowens** [comment]
The honey pot form field I implemented is pretty soft security in that a spam bot executing the on form submit event handler could bypass it. If we actually have a problem with spam we can consider making it harder, but I don't want to fuck over users who use the browser's autocomplete.
