### ISSUE TITLE
Pretty dates

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#30]
For the essay index and other things, it would be nicer to have more readable dates. See the google drive document index.

**Comment by al63** [comment]
I ALREADY MADE THEM PRETTY

**Comment by jbowens** [comment]
:sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles:

**Comment by bryceAebi** [comment]
oops i opened another issue for this
