### ISSUE TITLE
clientside form validation: check max-length of strings

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#32]

**Comment by jbowens** [comment]
What is this for? Can we just set a maxlength attribute?

**Comment by bryceAebi** [comment]
yes. please set first and last name to 20, password to 30, email to 40. i'll create corresponding clientside checks. it's just so no one tries to dump something huge in our fields to break something

**Comment by jbowens** [comment]
oh so this should read server-side, not client-side?

**Comment by bryceAebi** [comment]
it should read both

**Comment by al63** [comment]
First name and last name are already limited to 30 and email to 80. I dont see the point of changing these arbitrarily

**Comment by bryceAebi** [comment]
that's fine. but we should also add a limit to password. we just needed to be on the same page about the lengths so that the clientside validation matches the serverside

**Comment by jbowens** [comment]
wait why limit passwords? isn't that just limiting the password space? is there any downside to unbounded passwords? we're just going to store a fixed-size hash anyways

**Comment by bryceAebi** [comment]
sounds reasonable. k so i guess the original issue, clientside validation, was correct
