### ISSUE TITLE
editor: random align bug

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#46]
to reproduce: new doc -> write a few words on like 10 lines. select all. align right

js error: 

Object
message: "Failed to execute 'setEnd' on 'Range': The node provided was null."
name: "NotFoundError"
path: "/essays/edit/42"
stack: "Error: Failed to execute 'setEnd' on 'Range': The node provided was null.↵    at Error (native)↵    at Object.$.extend.setCaret (http://localhost:3000/static/js/essays/document.js:332:16)↵    at http://localhost:3000/static/js/essays/editor.js:26:22↵    at HTMLButtonElement.<anonymous> (http://localhost:3000/static/js/errors.js:33:11)↵    at HTMLButtonElement.o.event.dispatch (http://localhost:3000/static/js/include/jquery-2.1.0.min.js:3:6055)↵    at HTMLButtonElement.r.handle (http://localhost:3000/static/js/include/jquery-2.1.0.min.js:3:2830)"
type: "error"
url: "http://localhost:3000/essays/edit/42"
user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.116 Safari/537.36"

**Comment by jbowens** [comment]
Is this still around? I may have accidentally fixed it, and I'm unable to reproduce.

**Comment by jbowens** [comment]
can't repro
