### ISSUE TITLE
editor: highlighting multiple lines

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#49]
when you highlight multiple lines, the highlighting extends beyond the boundaries of the page. this is purely an aesthetic issue

**Comment by jbowens** [comment]
Can you provide a screenshot? Unable to reproduce

**Comment by bryceAebi** [comment]
![screen shot 2014-04-18 at 6 07 55 pm](https://cloud.githubusercontent.com/assets/3914975/2746380/184f7472-c746-11e3-8494-5653339aa86d.png)

appears to only happen in readonly mode
