### ISSUE TITLE
If essay deleted, review assignments should be deleted

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#75]
if the essay is deleted but there was already a review requested, the links to that review under **Assignments** and **Notifications** should be deleted. 

right now they just have links to 404s

**Comment by bryceAebi** [comment]
actually, it's probably best to remove the link from **Assignments** and have the link in **Notifications** go to an error page explaining that the essay was deleted

**Comment by al63** [comment]
this functionality already exists. when an essay is deleted it cascades and deletes the associated review. the notification is left unchanged.
