### ISSUE TITLE
title deletes itself sometimes

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#79]
create a new document and quickly type in a title. stop typing and wait for save. Sometimes it randomly deletes. I think it has something to do with autosave/pinging the server for updates

**Comment by al63** [comment]
wow this is an awkward bug. it only occurs with new essays

**Comment by al63** [comment]
this should fix it, but it definitely made me realize we have a bigger problem. 4b76cad2a357cd43ffaa9a75bda690c8d6ecd6ce
