### ISSUE TITLE
delete sometimes doesn't work

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#87]
there is no error thrown. it just doesn't work occasionally. I'm not sure how to reproduce

**Comment by jbowens** [comment]
doesn't exist

**Comment by al63** [comment]
Peernote is an opinionated editor

**Comment by bryceAebi** [comment]
it seems to be caused by the editor losing focus. Delete doesn't break, the editor just loses focus when you press the delete key.

**Comment by bryceAebi** [comment]
it seems to happen when, after you've been writing for a while, you try to delete something at your current cursor position by holding delete. it'll delete a few characters then just lose focus

**Comment by bryceAebi** [comment]
nvm it doesn't only happen when holding delete
