### ISSUE TITLE
captcha sometimes dies

### ISSUE THREAD

**Issue by jbowens** [jbowens/peernote#9]
_allegedly_, the captcha sometimes shits itself with this error: http://cl.ly/image/2H1f0n091e45

i can fix it

**Comment by al63** [comment]
:hurtrealbad:

**Comment by jbowens** [comment]
:shipit:

**Comment by al63** [comment]
we will compromise on the priority

**Comment by jbowens** [comment]
can't repro

**Comment by jbowens** [comment]
alec is crazy

**Comment by al63** [comment]
:shipit:
