### ISSUE TITLE
Hacking the reviewer

### ISSUE THREAD

**Issue by bryceAebi** [jbowens/peernote#90]
If a user opens the console, they can make visible the hidden draft history and doc manager blocks. After doing so, they can move the document to the next draft (permanently), etc. 

With some inside knowledge, they can also switch the document to edit mode. I have no idea what this would even result in.

**Comment by al63** [comment]
This isn't a real issue.

All the API endpoints verify that the user's id equals the essay's id, so even if a different user tried to play with the dom, nothing would actually happen
